name       : mindforger
version    : 1.48.2
release    : 1
source     :
    - git|https://github.com/dvorka/mindforger : 1.48.2
license    : GPL-2.0-or-later
component  : office.notes
summary    : Thinking notebook and Markdown IDE
description: |
    MindForger is a thinking notebook and markdown IDE for creating, editing and managing all type of notes.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
build      : |
    # build dependencies
    pushd $workdir/deps/discount
    ./configure.sh
    %make
    popd

    %qmake -r mindforger.pro
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir

    # Remove the static library
    rm -rf $installdir/usr/lib
